### ISSUE TITLE
General questions regarding livereloadjs

### ISSUE THREAD

**Issue by mfridman** [loov/watchrun#6]
Greta stuff. I've been playing around with the `packaged` branch and go it working, but only for recompile.

Something unexpected came up

```dev.sh
#!/bin/sh

GOGC=off go build -i -o ./bin/web ./cmd/web/main.go
watchrun -verbose -monitor *.go ./bin/web
```

With `-monitor *.go` it hangs..

```
$ ./dev.sh 
Options:
    interval   :  300ms
    recursive  :  true
    monitoring :  [*.go]
    ignoring   :  [.* ~* *~ *.[ao] *.so *.obj *.log *.test *.prof *.exe *.dll]
    caring     :  []

Processes:
    ./bin/web
```

But if change `-monitor *.go` to `-monitor .` it works and recompiles on any change.

```dev.sh
$ ./dev.sh 
Options:
    interval   :  300ms
    recursive  :  true
    monitoring :  [.]
    ignoring   :  [.* ~* *~ *.[ao] *.so *.obj *.log *.test *.prof *.exe *.dll]
    caring     :  []

Processes:
    ./bin/web 

<< 2020-03-02 23:05:40.436258 -0500 EST m=+0.307991528 >>
<<  run: ./bin/web  >>
2020/03/02 23:05:40 serving..
```

---

I assume once the binary is running, we should be able to listen to a directory from within the app to reload a browser page.

Suppose I have this layout, and the following handler (chi.Router mux but that's irrelevant here)

```go
r.Handle("/~watch.js", watchjs.NewServer(watchjs.Config{
	Monitor: []string{
		filepath.Join("website", "templates", "**"),
		filepath.Join("website", "static", "**"),
	},
	Ignore: watchjs.DefaultIgnore,
}))
```

And everything inherits from `_base.tmpl` (which contains `<script src="/~watch.js"></script>`)

So ideally one would make a change in `/website/templates/index.tmpl` and the browser would get refreshed on whatever page it's on. Is this the intended behaviour? 

<img width="217" alt="Screen Shot 2020-03-02 at 11 12 22 PM" src="https://user-images.githubusercontent.com/6278244/75742518-ddfa8f00-5cdb-11ea-85eb-7d495e2f6ab4.png">

**Comment by egonelbre** [comment]
> watchrun -verbose -monitor *.go ./bin/web

Monitor here says, when any of the files matching glob `*.go` change then retrigger the specific command. If you have your `go` code in multiple folders, then you would need to monitor more than the "current folder .go files".

The reason `.` matches, is that it will match everything in the current directory. This include directories. Since recursive is "true" it will recurse into them.

The solution here is to use:

```
watchrun -verbose -care *.go ./bin/web
```

Care is more of a "filename" filter and doesn't change how "monitor" works.

Currently, the code won't be "recompiled" with that command, to recompile the code as well then:

```
watchrun -verbose -care *.go go build -i -o ./bin/web . == ./bin/web
```

The `==` here acts as shell `&&`.

--- 

For template recompiling take a look at: https://github.com/loov/watchrun/tree/master/examples/watchjs-templates.

Of course, you can also create a separate watcher for templates using https://godoc.org/github.com/loov/watchrun/watch#Watch and trigger recompilation from there.

**Comment by mfridman** [comment]
Great, thanks for the examples. Will close this issue.
